# Generated by Django 6.1.2 on 2026-10-09 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150)),
                ("password_hash", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "role",
                    models.CharField(
                        choices=[("tenant", "Tenant"), ("landlord", "Landlord")],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "code_sent_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_user_id_214752_idx",
        ),
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
