# Generated by Django 6.1.1 on 2026-10-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[("Murang'a Town", "Murang'a Town"), ('Mjini', 'Mjini'), ('Mukuyu Market', 'Mukuyu Market'), ('Area 4 near small gate', 'Area 4 near small gate')], max_length=100, unique=True),
        ),
    ]
